
package cn.gov.ynhrss.baseinfo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "bizPortType", targetNamespace = "http://www.ynhrss.gov.cn/baseinfo")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BizPortType {


    /**
     * 
     * @param parameter
     */
    @WebMethod(action = "bizOP")
    public void bizOP(
        @WebParam(name = "bizenv", targetNamespace = "http://www.ynhrss.gov.cn/baseinfo", mode = WebParam.Mode.INOUT, partName = "parameter")
        Holder<Bizenv> parameter);

}
