
package cn.gov.ynhrss.baseinfo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "bizService", targetNamespace = "http://www.ynhrss.gov.cn/baseinfo", wsdlLocation = "http://10.176.59.2:7003/services/cardManagement/CardMngmntService?wsdl")
public class BizService
    extends Service
{

    private final static URL BIZSERVICE_WSDL_LOCATION;
    private final static WebServiceException BIZSERVICE_EXCEPTION;
    private final static QName BIZSERVICE_QNAME = new QName("http://www.ynhrss.gov.cn/baseinfo", "bizService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.176.59.2:7003/services/cardManagement/CardMngmntService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BIZSERVICE_WSDL_LOCATION = url;
        BIZSERVICE_EXCEPTION = e;
    }

    public BizService() {
        super(__getWsdlLocation(), BIZSERVICE_QNAME);
    }

    public BizService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BIZSERVICE_QNAME, features);
    }

    public BizService(URL wsdlLocation) {
        super(wsdlLocation, BIZSERVICE_QNAME);
    }

    public BizService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BIZSERVICE_QNAME, features);
    }

    public BizService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BizService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BizPortType
     */
    @WebEndpoint(name = "bizPortType")
    public BizPortType getBizPortType() {
        return super.getPort(new QName("http://www.ynhrss.gov.cn/baseinfo", "bizPortType"), BizPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BizPortType
     */
    @WebEndpoint(name = "bizPortType")
    public BizPortType getBizPortType(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.ynhrss.gov.cn/baseinfo", "bizPortType"), BizPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BIZSERVICE_EXCEPTION!= null) {
            throw BIZSERVICE_EXCEPTION;
        }
        return BIZSERVICE_WSDL_LOCATION;
    }

}
