
package cn.gov.ynhrss.psp;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ynhrsspspservice", targetNamespace = "http://www.ynhrss.gov.cn/psp", wsdlLocation = "http://192.168.205.50:8280/services/ynhrsspspservice?wsdl")
public class Ynhrsspspservice
    extends Service
{

    private final static URL YNHRSSPSPSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(cn.gov.ynhrss.psp.Ynhrsspspservice.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = cn.gov.ynhrss.psp.Ynhrsspspservice.class.getResource(".");
            url = new URL(baseUrl, "http://192.168.205.50:8280/services/ynhrsspspservice?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://192.168.205.50:8280/services/ynhrsspspservice?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        YNHRSSPSPSERVICE_WSDL_LOCATION = url;
    }

    public Ynhrsspspservice(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Ynhrsspspservice() {
        super(YNHRSSPSPSERVICE_WSDL_LOCATION, new QName("http://www.ynhrss.gov.cn/psp", "ynhrsspspservice"));
    }

    /**
     * 
     * @return
     *     returns YnhrssPSPPortType
     */
    @WebEndpoint(name = "YnhrssPSPPortType")
    public YnhrssPSPPortType getYnhrssPSPPortType() {
        return super.getPort(new QName("http://www.ynhrss.gov.cn/psp", "YnhrssPSPPortType"), YnhrssPSPPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns YnhrssPSPPortType
     */
    @WebEndpoint(name = "YnhrssPSPPortType")
    public YnhrssPSPPortType getYnhrssPSPPortType(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.ynhrss.gov.cn/psp", "YnhrssPSPPortType"), YnhrssPSPPortType.class, features);
    }

}
